# Generated by Django 4.1 on 2022-09-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["completed", "-updated_at"]},
        ),
    ]
